
var _data = [
  ["Afghanistan","AF","Badakhshan|Badghis|Baghlan|Balkh|Bamyan|Daykundi|Farah|Faryab|Ghazni|Ghor|Helmand|Herat|Jawzjan|Kabul|Kandahar|Kapisa|Khost|Kunahra|Kunduz|Laghman|Logar|Nangarhar|Nimroz|Nooristan|Paktia|Paktika|Panjsher|Parwan|Samangan|Sar-I-Pul|Takhar|Urozgan|Wardak|Zabul"],
  ["Åland Islands","AX","Ålands"],
  ["Albania","AL","Berat|Dibër|Durrës|Elbasan|Fier|Gjirokastër|Korçë|Kukës|Lezhë|Shkodër|Tiranë|Vlorë"],
  ["Algeria","DZ","Adrar|Aïn Defla|Aïn Témouchent|Alger|Annaba|Batna|Béchar|Béjaïa|Biskra|Blida|Bordj Bou Arréridj|Bouira|Boumerdès|Chlef|Constantine|Djelfa|El Bayadh|El Oued|El Taref|Ghardaïa|Guelma|Illizi|Jijel|Khenchela|Laghouat|Mascara|Médéa|Mila|Mostaganem|M'Sila|Naâma|Oran|Ouargla|Oum el Bouaghi|Relizane|Saïda|Sétif|Sidi Bel Abbès|Skikda|Souk Ahras|Tamanrasset|Tébessa|Tiaret|Tindouf|Tipaza|Tissemsilt|Tizi Ouzou|Tlemcen"],
  ["American Samoa","AS","American Samoa"],
  ["Andorra","AD","Andorra La Vella|Canillo|Encamp|Escaldes-Engordany|La Massana|Ordino|Sant Julià de Lòria"],
  ["Angola","AO","Bengo|Benguela|Bié|Cabinda|Cuando Cubango|Cuanza Norte|Cuanza Sul|Cunene|Huambo|Huíla|Luanda|Lunda Norte|Lunda Sul|Malanje|Moxico|Namibe|Uíge|Zaire"],
  ["Anguilla","AI","Anguilla|Anguillita Island|Blowing Rock|Cove Cay|Crocus Cay|Deadman's Cay|Dog Island|East Cay|Little Island|Little Scrub Island|Mid Cay|North Cay|Prickly Pear Cays|Rabbit Island|Sandy Island/Sand Island|Scilly Cay|Scrub Island|Seal Island|Sombrero/Hat Island|South Cay|South Wager Island|West Cay"],
  ["Antarctica","AQ","Australian Antarctic Territory"],
  ["Antigua and Barbuda","AG","Antigua Island|Barbuda Island|Bird Island|Bishop Island|Blake Island|Crump Island|Dulcina Island|Exchange Island|Five Islands|Great Bird Island|Green Island|Guiana Island|Hawes Island|Hells Gate Island|Henry Island|Johnson Island|Kid Island|Lobster Island|Maiden Island|Moor Island|Nanny Island|Pelican Island|Prickly Pear Island|Rabbit Island|Red Head Island|Redonda Island|Sandy Island|Smith Island|The Sisters|Vernon Island|Wicked Will Island|York Island"],
  ["Argentina","AR","Buenos Aires|Capital Federal|Catamarca|Chaco|Chubut|Córdoba|Corrientes|Entre Ríos|Formosa|Jujuy|La Pampa|La Rioja|Mendoza|Misiones|Neuquén|Río Negro|Salta|San Juan|San Luis|Santa Cruz|Santa Fe|Santiago del Estero|Tierra del Fuego|Tucumán"],
  ["Armenia","AM","Aragatsotn|Ararat|Armavir|Gegharkunik|Kotayk|Lori|Shirak|Syunik|Tavush|Vayots Dzor|Yerevan"],
  ["Aruba","AW","Aruba"],
  ["Australia","AU","Australian Antarctic Territory|Australian Capital Territory|Christmas Island|Cocos|Heard Island|Jervis Bay Territory|McDonald Islands|New South Wales|Norfolk Island|Northern Territory|Queensland|South Australia|Tasmania|Victoria|Western Australia"],
  ["Austria","AT","Burgenland|Kärnten|Niederösterreich|Oberösterreich|Salzburg|Steiermark|Tirol|Vorarlberg|Wien"],
  ["Azerbaijan","AZ","Abşeron|Daglig-Shirvan|Gəncə-Qazax|Kəlbəcər-Laçın|Kur|Lənkəran-Astara|Nagorno-Karabakh|Naxçıvan|Orta Kur|Quba-Xaçmaz|Şəki-Zaqatala|Yukhari-Karabakh"],
  ["Bahamas","BS","Acklins Island|Berry Islands|Bimini|Black Point|Cat Island|Central Abaco|Crooked Island and Long Cay|East Grand Bahama|Exuma|Freeport|Fresh Creek|Governor's Harbour|Green Turtle Cay|Harbour Island|High Rock|Inagua|Kemps Bay|Long Island|Marsh Harbour|Mayaguana|Moore’s Island|New Providence|Nichollstown and Berry Islands|North Abaco|North Andros|North Eleuthera|Ragged Island|Rock Sound|San Salvador and Rum Cay|Sandy Point|South Abaco|South Andros|South Eleuthera|West Grand Bahama"],
  ["Bahrain","BH","Al Manama|Middle|Muharraq|Northern|Southern"],
  ["Bangladesh","BD","Barisal|Chittagong|Dhaka|Khulna|Rajshahi|Rangpur|Sylhet"],
  ["Barbados","BB","Christ Church|Saint Andrew|Saint George|Saint James|Saint John|Saint Joseph|Saint Lucy|Saint Michael|Saint Peter|Saint Philip|Saint Thomas"],
  ["Belarus","BY","Brest voblast|Gorod Minsk|Homiel voblast|Hrodna voblast|Mahilyow voblast|Minsk voblast|Vitsebsk voblast"],
  ["Belgium","BE","Bruxelles-Capitale|Région Flamande|Région Wallonië"],
  ["Belize","BZ","Belize District|Cayo District|Corozal District|Orange Walk District|Stann Creek District|Toledo District"],
  ["Benin","BJ","Alibori|Atakora|Atlantique|Borgou|Collines Department|Donga|Kouffo|Littoral Department|Mono Department|Ouémé|Plateau|Zou"],
  ["Bermuda","BM","City of Hamilton|Devonshire Parish|Hamilton Parish|Paget Parish|Pembroke Parish|Sandys Parish|Smith's Parish|Southampton Parish|St. George's Parish|Town of St. George|Warwick Parish"],
  ["Bhutan","BT","Bumthang|Chhukha|Dagana|Gasa|Haa|Lhuntse|Mongar|Paro|Pemagatshel|Punakha|Samdrup Jongkhar|Samtse|Sarpang|Thimphu|Trashigang|Trashiyangtse|Trongsa|Tsirang|Wangdue Phodrang|Zhemgang"],
  ["Bolivia","BO","Beni|Chuquisaca|Cochabamba|La Paz|Oruro|Pando|Potosí|Santa Cruz|Tarija"],
  ["Bonaire, Sint Eustatius and Saba","BQ","Bonaire|Saba Isand|Sint Eustatius"],
  ["Bosnia and Herzegovina","BA","Brčko Distrikt|Federacija Bosne i Hercegovine|Republika Srpska"],
  ["Botswana","BW","Central|Ghanzi|Kgalagadi|Kgatleng|Kweneng|North West|North-East|South East|Southern"],
  ["Bouvet Island","BV","Bouvet Island"],
  ["Brazil","BR","Centro-Oeste|Nordeste|Norte|Sudeste|Sul"],
  ["British Indian Ocean Territory","IO","Chagos Islands"],
  ["Virgin Islands, British","VG","Anegada|Jost Van Dyke|Other Islands|Tortola|Virgin Gorda"],
  ["Brunei Darussalam","BN","Belait|Brunei Muara|Temburong|Tutong"],
  ["Bulgaria","BG","Blagoevgrad|Burgas|Dobrich|Gabrovo|Jambol|Khaskovo|Kjustendil|Kurdzhali|Lovech|Montana|Pazardzhik|Pernik|Pleven|Plovdiv|Razgrad|Ruse|Shumen|Silistra|Sliven|Smoljan|Sofija|Sofija-Grad|Stara Zagora|Turgovishhe|Varna|Veliko Turnovo|Vidin|Vraca"],
  ["Burkina Faso","BF","Balé|Bam/Lake Bam|Banwa Province|Bazèga|Bougouriba|Boulgou Province|Boulkiemdé|Comoé/Komoe|Ganzourgou Province|Gnagna|Gourma Province|Houet|Ioba|Kadiogo|Kénédougou|Komondjari|Kompienga|Kossi Province|Koulpélogo|Kouritenga|Kourwéogo|Léraba|Loroum|Mouhoun|Namentenga|Naouri/Nahouri|Nayala|Noumbiel|Oubritenga|Oudalan|Passoré|Poni|Sanguié|Sanmatenga|Séno|Sissili|Soum|Sourou|Tapoa|Tui/Tuy|Yagha|Yatenga|Ziro|Zondoma|Zoundwéogo"],
  ["Burundi","BI","Bubanza|Bujumbura Mairie|Bujumbura Rural|Bururi|Cankuzo|Cibitoke|Gitega|Karuzi|Kayanza|Kirundo|Makamba|Muramvya|Muyinga|Mwaro|Ngozi|Rutana|Ruyigi"],
  ["Cambodia","KH","Banteay Meanchey|Battambang|Kampong Cham|Kampong Chhnang|Kampong Speu|Kampong Thom|Kampot|Kandal|Koh Kong|Kratie|Krong Kep|Krong Pailin|Krong Preah Sihanouk|Mondol Kiri|Oudor MeanChey|Phnom Penh|Preah Vihear|Prey Veng|Pursat|RatanaKiri|Siem Reap|Stung Treng|Svay Rieng|Takéo"],
  ["Cameroon","CM","Adamaoua|Centre|Est|Extrême-Nord|Littoral|Nord|Nord-Ouest|Ouest|Sud|Sud-Ouest"],
  ["Canada","CA","Alberta|British Columbia|Manitoba|New Brunswick|Newfoundland and Labrador|Northwest Territories|Nova Scotia|Nunavut|Ontario|Prince Edward Island|Quebec|Saskatchewan|Yukon Territory"],
  ["Cape Verde","CV","Boa Vista|Brava|Calheta de São Miguel|Maio|Mosteiros|Paúl|Porto Novo|Praia|Ribeira Brava|Ribeira Grande|Sal|Santa Catarina|Santa Cruz|São Domingos|São Filipe|São Nicolau|São Vicente|Tarrafal|Tarrafal de São Nicolau"],
  ["Cayman Islands","KY","Cayman Brac|Grand Cayman|Little Cayman"],
  ["Central African Republic","CF","Bamingui-Bangoran|Bangui|Basse-Kotto|Haute-Kotto|Haut-Mbomou|Kémo|Lobaye|Mambéré-Kadéï|Mbomou|Nana-Grebizi|Nana-Mambéré|Ombella-M'Poko|Ouaka|Ouham|Ouham Péndé|Sangha-Mbaéré|Vakaga"],
  ["Chad","TD","Barh el Gazel|Batha|Borkou|Chari-Baguirmi|Ennedi|Guéra|Hadjer-Lamis|Kanem|Lac|Logone Occidental|Logone Oriental|Mandoul|Mayo-Kebbi Est|Mayo-Kebbi Ouest|Moyen-Chari|N'Djamena|Ouaddaï|Salamat|Sila|Tandjilé|Tibesti|Wadi Fira"],
  ["Chile","CL","Aisén del General Carlos Ibáñez del Campo|Antofagasta|Araucanía|Arica y Parinacota|Atacama|Bío-Bío|Coquimbo|Libertador General Bernardo O'Higgins|Los Lagos|Los Ríos|Magallanes y Antartica Chilena|Marga-Marga|Maule|Región Metropolitana de Santiago|Tarapacá|Valparaíso"],
  ["China","CN","Anhui|Beijing|Chongqing|Fujian|Gansu|Guangdong|Guangxi|Guizhou|Hainan|Hebei|Heilongjiang|Henan|Hong Kong|Hubei|Hunan|Inner Mongolia|Jiangsu|Jiangxi|Jilin|Liaoning|Macau|Ningxia|Qinghai|Shaanxi|Shandong|Shanghai|Shanxi|Sichuan|Tianjin|Tibet|Xinjiang|Yunnan|Zhejiang"],
  ["Christmas Island","CX","Christmas Island"],
  ["Cocos (Keeling) Islands","CC","Cocos"],
  ["Colombia","CO","Amazonas|Antioquia|Arauca|Archipiélago de San Andrés|Atlántico|Bogotá D.C.|Bolívar|Boyacá|Caldas|Caquetá|Casanare|Cauca|Cesar|Chocó|Córdoba|Cundinamarca|Guainía|Guaviare|Huila|La Guajira|Magdalena|Meta|Nariño|Norte de Santander|Putumayo|Quindío|Risaralda|Santander|Sucre|Tolima|Valle del Cauca|Vaupés|Vichada"],
  ["Comoros","KM","Anjouan|Grande Comore|Mwali"],
  ["Congo, Republic of the (Brazzaville)","CG","Bouenza|Brazzaville|Cuvette|Cuvette-Ouest|Kouilou|Lékoumou|Likouala|Niari|Plateaux|Pointe-Noire|Pool|Sangha"],
  ["Congo, the Democratic Republic of the","CD","Bandundu|Bas-Congo|Équateur|Kasaï-Occidental|Kasaï-Oriental|Katanga|Kinshasa|Maniema|Nord-Kivu|Orientale|Sud-Kivu"],
  ["Cook Islands","CK","Cook Islands"],
  ["Costa Rica","CR","Alajuela|Cartago|Guanacaste|Heredia|Limón|Puntarenas|San José"],
  ["Croatia","HR","Bjelovarsko-Bilogorska|Brodsko-Posavska|Dubrovačko-Neretvanska|Grad Zagreb|Istarska|Karlovačka|Koprivničko-Križevačka|Krapinsko-Zagorska|Ličko-Senjska|Međimurska|Osječko-Baranjska|Požeško-Slavonska|Primorsko-Goranska|Šibensko-Kninska|Sisačko-Moslavačka|Splitsko-Dalmatinska|Varaždinska|Virovitičko-Podravska|Vukovarsko-Srijemska|Zadarska|Zagrebačka"],
  ["Cuba","CU","Artemisa|Camagüey|Ciego de Ávila|Cienfuegos|Granma|Guantánamo|Holguín|Isla de la Juventud|La Habana|Las Tunas|Matanzas|Mayabeque|Pinar del Río|Sancti Spíritus|Santiago de Cuba|Villa Clara"],
  ["Curaçao","CW","Curaçao"],
  ["Cyprus","CY","Ammochostos|Keryneia|Larnaka|Lefkosia|Lemesos|Pafos"],
  ["Czech Republic","CZ","Hlavní město Praha|Jihočeský kraj|Jihomoravský kraj|Karlovarský kraj|Královéhradecký kraj|Liberecký kraj|Moravskoslezský kraj|Olomoucký kraj|Pardubický kraj|Plzeňský kraj|Středočeský kraj|Ústecký kraj|Vysočina|Zlínský kraj"],
  ["Denmark","DK","Hovedstaden|Kujalleq|Midtjylland|Norderøerne|Nordjylland|Østerø|Qaasuitsup|Qeqqata|Sandø|Sermersooq|Sjælland|Strømø|Suderø|Syddanmark|Vågø"],
  ["Djibouti","DJ","Ali Sabieh|Arta|Dikhil|Obock|Tadjourah"],
  ["Dominica","DM","Saint Andrew Parish|Saint David Parish|Saint George Parish|Saint John Parish|Saint Joseph Parish|Saint Luke Parish|Saint Mark Parish|Saint Patrick Parish|Saint Paul Parish|Saint Peter Parish"],
  ["Dominican Republic","DO","Cibao Central|Del Valle|Distrito Nacional|Enriquillo|Norcentral|Nordeste|Noroeste|Norte|Valdesia"],
  ["Timor-Leste","TL","Aileu|Ainaro|Baucau|Bobonaro|Covalima|Dili|Ermera|Lautem|Liquiçá|Manatuto|Manufahi|Oecusse|Viqueque"],
  ["Ecuador","EC","Azuay|Bolívar|Cañar|Carchi|Chimborazo|Cotopaxi|El Oro|Esmeraldas|Galápagos|Guayas|Imbabura|Loja|Los Ríos|Manabí|Morona-Santiago|Napo|Orellana|Pastaza|Pichincha|Santa Elena|Santo Domingo de los Tsáchilas|Sucumbíos|Tungurahua|Zamora-Chinchipe"],
  ["Egypt","EG","Alexandria|Aswan|Asyout|Bani Sueif|Beheira|Cairo|Daqahlia|Dumiat|El Bahr El Ahmar|El Ismailia|El Suez|El Wadi El Gedeed|Fayoum|Gharbia|Giza|Helwan|Kafr El Sheikh|Luxor|Matrouh|Menia|Menofia|North Sinai|Port Said|Qalubia|Qena|Sharqia|Sixth of October|Sohag|South Sinai"],
  ["El Salvador","SV","Ahuachapán|Cabañas|Chalatenango|Cuscatlán|La Libertad|La Paz|La Unión|Morazán|San Miguel|San Salvador|San Vicente|Santa Ana|Sonsonate|Usulután"],
  ["Equatorial Guinea","GQ","Región Continental|Región Insular"],
  ["Eritrea","ER","Anseba|Debub|Debub-Keih-Bahri|Gash-Barka|Maekel|Semien-Keih-Bahri"],
  ["Estonia","EE","Harjumaa|Hiiumaa|Ida-Virumaa|Järvamaa|Jõgevamaa|Läänemaa|Lääne-Virumaa|Pärnumaa|Põlvamaa|Raplamaa|Saaremaa|Tartumaa|Valgamaa|Viljandimaa|Võrumaa"],
  ["Ethiopia","ET","Addis Ababa|Afar|Amhara|Benshangul-Gumaz|Dire Dawa|Gambela|Harari|Oromia|Somali|Southern Nations Nationalities and People's Region|Tigray"],
  ["Falkland Islands (Islas Malvinas)","FK","Barren Island|Beauchene Island|Beaver Island|Bleaker Island|Box Island|Brocken Island|Burnt Island|Carcass Island|Christmas Island|Cow Island|Cross Island|Double Creek Islands|Dry Island|Dyke Island|East Falkland|Eddystone Island|George Island|Golding Island|Great Island|Jason Islands|Keppel Island|Middle Island|New Island|Outer Island|Passage Island|Peat Island|Pebble Island|Philmore Island|Port Patterson|Ruggles Island|Sandbar Island|Saunders Island|Sea Lion Island|Sedge Island|Speedwell Island|Spring Point Island|Staats Island|Swan Island|Tickel Island|Tussac Island|Weddell Island|West Falkland|West Island|West Point Island|West Swan island|Wolfe Island"],
  ["Faroe Islands","FO","Borðoy|Eysturoy|Fugloy|Hestur|Kalsoy|Koltur|Kunoy|Mykines|Nólsoy|Sandoy|Skúvoy|Stóra Dímun|Streymoy|Suðuroy|Svínoy|Vágar|Viðoy"],
  ["Fiji","FJ","Central|Eastern|Northern|Rotuma|Western"],
  ["Finland","FI","Ahvenanmaan lääni|Etelä-Suomen lääni|Itä-Suomen lääni|Länsi-Suomen lääni|Lapin lääni|Oulun lääni"],
  ["France","FR","Alsace|Aquitaine|Arrondissement de Saint-Martin|Auvergne|Basse-Normandie|Bourgogne|Bretagne|Centre|Champagne-Ardenne|Corse|Franche-Comté|Guadeloupe|Guyane française|Haute-Normandie|Île de Clipperton|Île-de-France|La Réunion|Languedoc-Roussillon|Limousin|Lorraine|Martinique|Mayotte|Midi-Pyrénées|Nord-Pas-de-Calais|Nouvelle-Calédonie|Pays de la Loire|Picardie|Poitou-Charentes|Polynésie Française|Provence-Alpes-Côte d'Azur|Rhône-Alpes|Saint-Barthélemy|Saint-Pierre-et-Miquelon|Terres australes françaises|Wallis-et-Futuna"],
  ["French Guiana","GF","Guyane"],
  ["French Polynesia","PF","Polynésie Française"],
  ["French Southern and Antarctic Lands","TF","Terres australes françaises"],
  ["Gabon","GA","Estuaire|Haut-Ogooué|Moyen-Ogooué|Ngounié|Nyanga|Ogooué-Ivindo|Ogooué-Lolo|Ogooué-Maritime|Woleu-Ntem"],
  ["Gambia, The","GM","Banjul City|Central River|Lower River|North Bank|Upper River|Western"],
  ["Georgia","GE","Abashis Raioni|Abkhazia|Adigenis Raioni|Ajaria|Akhalgoris Raioni|Akhalkalakis Raioni|Akhaltsikhis Raioni|Akhmetis Raioni|Ambrolauris Raioni|Aspindzis Raioni|Baghdat is Raioni|Bolnisis Raioni|Borjomis Raioni|Chiatura|Chkhorotsqus Raioni|Chokhatauris Raioni|Dedoplistsqaros Raioni|Dmanisis Raioni|Dushetis Raioni|Gardabanis Raioni|Gori|Goris Raioni|Gurjaanis Raioni|Javis Raioni|Karelis Raioni|Kaspis Raioni|Kharagaulis Raioni|Khashuris Raioni|Khobis Raioni|Khonis Raioni|Kutaisi|Lagodekhis Raioni|Lanchkhutis Raioni|Lentekhis Raioni|Marneulis Raioni|Martvilis Raioni|Mestiis Raioni|Mtskhetis Raioni|Ninotsmindis Raioni|Onis Raioni|Ozurget is Raioni|Poti|Qazbegis Raioni|Qvarlis Raioni|Rustavi|Sachkheris Raioni|Sagarejos Raioni|Samtrediis Raioni|Senakis Raioni|Sighnaghis Raioni|Tbilisi|Telavis Raioni|Terjolis Raioni|Tetritsqaros Raioni|Tianetis Raioni|Tqibuli|Tsageris Raioni|Tsalenjikhis Raioni|Tsalkis Raioni|Tsqaltubo|Vanis Raioni|Zestaponis Raioni|Zugdidi|Zugdidis Raioni"],
  ["Germany","DE","Baden-Württemberg|Bayern|Berlin|Brandenburg|Bremen|Hamburg|Hessen|Mecklenburg-Vorpommern|Niedersachsen|Nordrhein-Westfalen|Rheinland-Pfalz|Saarland|Sachsen|Sachsen-Anhalt|Schleswig-Holstein|Thüringen"],
  ["Ghana","GH","Ashanti|Brong-Ahafo|Central|Eastern|Greater Accra|Northern|Upper East|Upper West|Volta|Western"],
  ["Gibraltar","GI","Gibraltar"],
  ["Greece","GR","Attica|Central Greece|Central Macedonia|Crete|East Macedonia And Thrace|Epirus|Ionian Islands|North Aegean|Peloponnese|South Aegean|Thessaly|West Greece|West Macedonia"],
  ["Greenland","GL","Grønland"],
  ["Grenada","GD","Carriacou and Petit Martinique|Frigate Island|Large Island|Mushroom Island|Saline Island"],
  ["Guadeloupe","GP","Guadeloupe"],
  ["Guam","GU","Guam"],
  ["Guatemala","GT","Alta Verapaz|Baja Verapaz|Chimaltenango|Chiquimula|El Progreso|Escuintla|Huehuetenango|Izabal|Jalapa|Jutiapa|Petén|Quetzaltenango|Quiché|Retalhuleu|Sacatepéquez|San Marcos|Santa Rosa|Sololá|Suchitepéquez|Totonicapán|Zacapa"],
  ["Guernsey","GG","Guernsey Channel Islands"],
  ["Guinea","GN","Boké|Conakry|Faranah|Kankan|Labé|Mamou|Nzérékoré|Préfecture de Kindia"],
  ["Guinea-Bissau","GW","Bafatá|Biombo|Bissau|Bolama|Cacheu|Gabú|Oio|Quinara|Tombali"],
  ["Guyana","GY","Barima-Waini|Cuyuni-Mazaruni|Demerara-Mahaica|East Berbice-Corentyne|Essequibo Islands-West Demerara|Mahaica-Berbice|Pomeroon-Supenaam|Potaro-Siparuni|Upper Demerara-Berbice|Upper Takutu-Upper Essequibo"],
  ["Haiti","HT","Artibonite|Centre|Grand'Anse|Nippes|Nord|Nord-Est|Nord-Ouest|Ouest|Sud|Sud-Est"],
  ["Heard Island and McDonald Islands","HM","Heard Island|McDonald Islands"],
  ["Honduras","HN","Atlántida|Choluteca|Colón|Comayagua|Copán|Cortés|El Paraíso|Francisco Morazán|Gracias a Dios|Intubucá|Islas de la Bahía|La Paz|Lempira|Ocotepeque|Olancho|Santa Bárbara|Valle|Yoro"],
  ["Hong Kong","HK","Eastern|Islands|Kowloon City|Kwai Tsing|Kwun Tong|North|Sai Kung|Sha Tin|Sham Shui Po|Southern|Tai Po|Tsuen Wan|Tuen Mun|Wong Tai Sin|Yau Tsim Mong|Yuen Long"],
  ["Hungary","HU","Bács-Kiskun|Baranya|Békés|Borsod-Abaúj-Zemplén|Budapest|Csongrád|Fejér|Győr-Moson-Sopron|Hajdú-Bihar|Heves|Jász-Nagykun-Szolnok|Komárom-Esztergom|Nógrád|Pest|Somogy|Szabolcs-Szatmár-Bereg|Tolna|Vas|Veszprém|Zala"],
  ["Iceland","IS","Austurland|Höfuðborgarsvæði utan Reykjavíkur|Norðurland eystra|Norðurland vestra|Suðurland|Suðurnes|Vestfirðir|Vesturland"],
  ["India","IN","Andaman and Nicobar Islands|Andhra Pradesh|Arunachal Pradesh|Assam|Bihar|Chandigarh|Chhattisgarh|Dadra and Nagar Haveli|Daman and Diu|Delhi|Goa|Gujarat|Haryana|Himachal Pradesh|Jammu and Kashmir|Jharkhand|Karnataka|Kerala|Lakshadweep|Madhya Pradesh|Maharashtra|Manipur|Meghalaya|Mizoram|Nagaland|Orissa|Puducherry|Punjab|Rajasthan|Sikkim|Tamil Nadu|Tripura|Uttar Pradesh|Uttarakhand|West Bengal"],
  ["Indonesia","ID","Aceh|Bali|Bangka-Belitung|Banten|Bengkulu|Gorontalo|Jakarta|Jambi|Java Central|Java East|Java West|Kalimantan Central|Kalimantan East|Kalimantan South|Kalimantan West|Lampung|Maluku|Maluku North|Nusa Tenggara East|Nusa Tenggara West|Papua|Papua West|Riau|Riau Islands|Sulawesi Central|Sulawesi North|Sulawesi South|Sulawesi South East|Sulawesi West|Sumatra North|Sumatra South|Sumatra West|Yogyakarta"],
  ["Iran, Islamic Republic of","IR","Ardabil|Azarbayjan-e Gharbi|Azarbayjan-e Sharqi|Bushehr|Chahar Mahall va Bakhtiari|Esfahan|Fars|Gilan|Golestan|Hamadan|Hormozgan|Ilam|Kerman|Kermanshah|Khuzestan|Kohgiluyeh va Buyer Ahmad|Kordestan|Lorestan|Markazi|Mazandaran|North Khorasan|Qazvin|Qom|Razavi Khorasan|Semnan|Sistan va Baluchestan|South Khorasan|Tehran|Yazd|Zanjan"],
  ["Iraq","IQ","Al Anbār|Al Başrah|Al Muthanná|Al Qādisīyah|An Najaf|Arbīl|As Sulaymānīyah|At Ta'mīm|Bābil|Baghdād|Dahūk|Dhī Qār|Diyālá|Karbalā'|Maysān|Nīnawá|Şalāḩ ad Dīn|Wāsiţ"],
  ["Ireland","IE","Connacht|Leinster|Munster|Ulster"],
  ["Isle of Man","IM","Isle of Man"],
  ["Israel","IL","Central District|Haifa District|Jerusalem District|Judea and Samaria Area|Northern District|Southern District|Tel Aviv District"],
  ["Italy","IT","Abruzzi|Basilicata|Calabria|Campania|Emilia-Romagna|Friuli-Venezia Giulia|Lazio|Ligúria|Lombardia|Marche|Molise|Piemonte|Puglia|Sardegna|Sicilia|Toscana|Trentino-Alto Adige|Umbría|Valle D'Aosta|Veneto"],
  ["Côte d'Ivoire, Republic of","CI","Agnéby|Bafing|Bas-Sassandra|Denguélé|Dix-Huit Montagnes|Fromager|Haut-Sassandra|Lacs|Lagunes|Marahoué|Moyen-Cavally|Moyen-Comoé|N'zi-Comoé|Savanes|Sud-Bandama|Sud-Comoé|Vallée du Bandama|Worodougou|Zanzan"],
  ["Jamaica","JM","Clarendon|Hanover|Kingston|Manchester|Portland|Saint Andrew|Saint Ann|Saint Catherine|Saint Elizabeth|Saint James|Saint Mary|Saint Thomas|Trelawny|Westmoreland"],
  ["Japan","JP","Chubu|Chugoku|Hokkaido|Kansai|Kanto|Kyushu|Shikoku|Tohoku"],
  ["Jersey","JE","Jersey Channel Islands"],
  ["Jordan","JO","Ajlun|Al Aqabah|Al Balqa|Al Karak|Al Mafraq|Amman|Area not categorized|At Tafilah|Az Zarqa|Irbid|Jarash|Ma'an|Madaba"],
  ["Kazakhstan","KZ","Akmola|Aktobe|Almaty City|Almaty Province|Astana City|Atyrau|East Kazakhstan|Karagandy|Kostanay|Kyzylorda|Mangystau region|North Kazakhstan|Pavlodar|South Kazakhstan|West Kazakhstan|Zhambyl"],
  ["Kenya","KE","Central|Coast|Eastern|Nairobi|North Eastern|Nyanza|Rift Valley|Western"],
  ["Kiribati","KI","Gilbert Islands|Line Islands|Phoenix Islands"],
  ["Kosovo","XK","Đakovica|Gnjilane|Kosovska Mitrovica|Peć|Priština|Prizren|Uroševac"],
  ["Kuwait","KW","Al-Ahmadi|Al-Asimah|Al-Farwaniyah|Al-Jahra|Hawalli|Mubarak Al-Kabeer"],
  ["Kyrgyzstan","KG","Batken Province|Bishkek City|Chuy Province|Issyk Kul Province|Jalal-Abad Province|Naryn Province|Osh City|Osh Province|Talas Province"],
  ["Lao People's Democratic Republic","LA","Attapeu Province|Bokeo Province|Bolikhamsai Province|Champasak Province|Houaphanh Province|Khammouane Province|Luang Namtha Province|Luang Prabang Province|Oudomxay Province|Phongsaly Province|Salavan Province|Savannakhet Province|Sayabouly Province|Sekong Province|Vientiane Prefecture|Vientiane Province|Xiangkhouang Province"],
  ["Latvia","LV","Kurzemes|Latgales|Rīgas|Vidzemes|Zemgales"],
  ["Lebanon","LB","Akkar|Baalbek Hermel|Beirut|Beqaa|Mount Lebanon|Nabatiye|North Lebanon|South Lebanon"],
  ["Lesotho","LS","Berea|Butha-Buthe|Leribe|Mafeteng|Maseru|Mohale's Hoek|Mokhotlong|Qacha's Nek|Quthing|Thaba-Tseka"],
  ["Liberia","LR","Bomi|Bong|Grand Bassa|Grand Cape Mount|Grand Gedeh|Grand Kru|Lofa|Margibi|Maryland|Monrovia / River Gee|Montserrado|Nimba|River Cess|Sinoe"],
  ["Libya","LY","Al Butnan|Al Jabal al Akhdar|Al Jabal al Gharbi|Al Jifarah|Al Jufrah|Al Kufrah|Al Marj|Al Murqub|Al Wahat|An Nuqat al Khams|Az Zawiyah|Banghazi|Derna|Ghat|Misratah|Murzuq|Nalut|Sabha|Surt|Tarabulus / Tsarrbuus|Tarhunah|Wadi al Shatii|Yafran|Zlitan"],
  ["Liechtenstein","LI","Balzers|Eschen|Gamprin|Mauren|Planken|Ruggell|Schaan|Schellenberg|Triesen|Triesenberg|Vaduz"],
  ["Lithuania","LT","Alytaus|Kauno|Klaipėdos|Marijampolės|Panevėžio|Šiaulių|Tauragės|Telšių|Utenos|Vilniaus"],
  ["Luxembourg","LU","Diekirch|Grevenmacher"],
  ["Macau","MO","Ilhas"],
  ["Macedonia, Republic of","MK","East|Northeast|Pelagonia|Polog|Skopje|Southeast|Southwest|Vardar"],
  ["Madagascar","MG","Antananarivo|Antsiranana|Fianarantsoa|Mahajanga|Toamasina|Toliara"],
  ["Malawi","MW","Balaka|Blantyre|Chikwawa|Chiradzulu|Chitipa|Dedza|Dowa|Karonga|Kasungu|Lilongwe|Machinga|Mangochi|Mchinji|Mulanje|Mwanza|Mzimba|Neno|Nkhata Bay|Nkhotakota|Nsanje|Ntcheu|Ntchisi|Phalombe|Rumphi|Salima|Thyolo|Zomba"],
  ["Malaysia","MY","Johor|Kedah|Kelantan|Melaka|Negeri Sembilan|Pahang|Perak|Perlis|Pulau Pinang|Sabah|Sarawak|Selangor|Terengganu|Wilayah Persekutuan Kuala Lumpur|Wilayah Persekutuan Labuan|Wilayah Persekutuan Putra Jaya"],
  ["Maldives","MV","Dhekunu|Malé|Mathi-Dhekunu|Mathi-Uthuru|Medhu|Medhu-Dhekunu|Medhu-Uthuru|Uthuru"],
  ["Mali","ML","Bamako|Gao|Kayes|Kidal|Koulikoro|Mopti|Ségou|Sikasso|Tombouctou"],
  ["Malta","MT","Comino|Gozo"],
  ["Marshall Islands","MH","Ralik Islands chain|Ratak chain"],
  ["Martinique","MQ","Région Martinique"],
  ["Mauritania","MR","Adrar|Assaba Region|Brakna|Dakhlet Nouadhibou|Gorgol|Guidimaka|Hodh Ech Chargui|Hodh El Gharbi|Inchiri|Nouakchott|Tagant|Tiris Zemmour|Trarza"],
  ["Mauritius","MU","Agaléga Islands|Cargados Carajos|Flacq|Grand Port|Moka|Pamplemousses|Plaines Wilhems|Port Louis|Rivière du Rempart|Rivière Noire|Rodrigues|Savanne"],
  ["Mayotte","YT","Région Mayotte"],
  ["Mexico","MX","Aguascalientes|Baja California|Baja California Sur|Campeche|Chiapas|Chihuahua|Coahuila|Colima|Distrito Federal|Durango|Guanajuato|Guerrero|Hidalgo|Jalisco|México|Michoacán|Morelos|Nayarit|Nuevo León|Oaxaca|Puebla|Querétaro|Quintana Roo|San Luis Potosí|Sinaloa|Sonora|Tabasco|Tamaulipas|Tlaxcala|Veracruz|Yucatán|Zacatecas"],
  ["Micronesia, Federated States of","FM","Chuuk|Kosrae|Pohnpei|Yap"],
  ["Moldova","MD","Anenii Noi|Bălţi|Basarabeasca|Briceni|Cahul|Călăraşi|Cantemir|Căuşeni|Chişinău|Cimişlia|Criuleni|Donduşeni|Drochia|Edineţ|Făleşti|Floreşti|Gagauzia|Glodeni|Hînceşti|Ialoveni|Leova|Nisporeni|Ocniţa|Orhei|Rezina|Rîşcani|Sîngerei|Şoldăneşti|Soroca|Ştefan Vodă|Străşeni|Taraclia|Teleneşti|Transnistria|Ungheni"],
  ["Monaco","MC","Fontvieille|Jardin Exotique/Les Révoires|La Condamine|Larvotto/Bas Moulins|Monaco Ville|Monte Carlo/Spélugues"],
  ["Mongolia","MN","Central region|Eastern region|Khangai region|Ulaanbaatar City|Western region"],
  ["Montenegro","ME","Andrijevica|Bar|Berane|Bijelo Polje|Budva|Cetinje|Danilovgrad|Herceg Novi|Kolašin|Kotor|Mojkovac|Nikšić|Plav|Pljevlja|Plužine|Podgorica|Rožaje|Šavnik|Tivat|Ulcinj|Žabljak"],
  ["Montserrat","MS","Saint Anthony Parish|Saint Georges Parish|Saint Peter Parish"],
  ["Morocco","MA","Chaouia-Ouardigha|Doukhala-Abda|Fès-Boulemane|Gharb-Chrarda-Beni Hssen|Grand Casablanca|Guelmim-Es Smara|Laâyoune-Boujdour-Sakia el Hamra|L'Oriental|Marrakech-Tensift-Al Haouz|Meknès-Tafilalet|Oued Ed-Dahab-Lagouira|Rabat-Salé-Zemmour-Zaër|Sous-Massa-Drâa|Tadla-Azilal|Tanger-Tétouan|Taza-Al Hoceima-Taounate"],
  ["Mozambique","MZ","Cabo Delgado|Gaza|Inhambane|Manica|Maputo|Nampula|Niassa|Sofala|Tete|Zambézia"],
  ["Myanmar","MM","Ayeyarwaddy|Bago|Chin|Kachin|Kayah|Kayin|Magway|Mandalay|Mon|Rakhine|Sagaing|Shan|Taninthayi|Yangon"],
  ["Namibia","NA","Erongo|Hardap|Karas|Khomas|Kunene|Ohangwena|Okavango|Omaheke|Omusati|Oshana|Oshikoto|Otjozondjupa|Zambezi"],
  ["Nauru","NR","Aiwo|Anabar|Anetan|Anibare|Baiti|Boe|Buada|Denigomodu|Ewa|Ijuw|Meneng|Nibok|Uaboe|Yaren"],
  ["Nepal","NP","Madhya Pashchimanchal|Madhyamanchal|Pashchimanchal|Purwanchal|Sudur Pashchimanchal"],
  ["Netherlands","NL","Aruba|Caribisch Nederland|Curaçao|Drenthe|Flevoland|Friesland|Gelderland|Groningen|Limburg|Noord-Brabant|Noord-Holland|Overijssel|Sint Maarten|Utrecht|Zeeland|Zuid-Holland"],
  ["Netherlands Antilles","AN","Netherlands Antilles"],
  ["New Caledonia","NC","Nouvelle-Calédonie"],
  ["New Zealand","NZ","Auckland|Bay of Plenty|Canterbury|Cook Islands|Gisborne|Hawke's Bay|Manawatu-Wanganui|Marlborough|Nelson|Niué|Northland|Otago|Southland|Taranaki|Tasman|Tokelau|Waikato|Wellington|West Coast"],
  ["Nicaragua","NI","Atlántico Norte|Atlántico Sur|Boaco|Carazo|Chinandega|Chontales|Estelí|Granada|Jinotega|León|Madriz|Managua|Masaya|Matagalpa|Nueva Segovia|Río San Juan|Rivas"],
  ["Niger","NE","Agadez|Diffa|Dosso|Maradi|Niamey|Tahoua|Tillabéri|Zinder"],
  ["Nigeria","NG","Abia|Abuja|Adamawa|Akwa Ibom|Anambra|Bauchi|Bayelsa|Benue|Borno|Cross River|Delta|Ebonyi|Edo|Ekiti|Enugu|Gombe|Imo|Jigawa|Kaduna|Kano|Katsina|Kebbi|Kogi|Kwara|Lagos|Nasarawa|Niger|Ogun|Ondo|Osun|Oyo|Plateau|Rivers|Sokoto|Taraba|Yobe|Zamfara"],
  ["Niue","NU","Niué"],
  ["Norfolk Island","NF","Norfolk Island"],
  ["Korea, Democratic People's Republic of (North)","KP","Chagang|Kangwon|North Hamgyong|North Hwanghae|North Pyongan|Pyongyang|Rason|Ryanggang|South Hamgyong|South Hwanghae|South Pyongan"],
  ["Northern Mariana Islands","MP","Northern Mariana Islands"],
  ["Norway","NO","Akershus|Aust-Agder|Bouvetøya|Buskerud|Finnmark|Hedmark|Hordaland|Jan Mayen|Møre og Romsdal|Nordland|Nord-Trøndelag|Oppland|Oslo|Østfold|Rogaland|Sogn og Fjordane|Sør-Trøndelag|Svalbard|Telemark|Troms|Vest-Agder|Vestfold"],
  ["Oman","OM","Al Batinah|Al Dakhliya|Al Dhahira|Al Wusta|Al-Sharqiya|Buraymi|Dhofar|Musandam|Muscat"],
  ["Pakistan","PK","Azad Kashmir|Balochistan|Federally Administered Tribal Areas|Gilgit-Baltistan|Islamabad|Khyber Pakhtunkhwa|Punjab|Sindh"],
  ["Palau","PW","Aimeliik|Airai|Angaur|Hatobohei|Kayangel|Koror|Melekeok|Ngaraard|Ngarchelong|Ngardmau|Ngatpang|Ngchesar|Ngeremlengui|Ngiwal|Peleliu|Sonsorol"],
  ["Palestine, State of","PS","Gaza|West Bank"],
  ["Panama","PA","Bocas del Toro|Chiriquí|Coclé|Colón|Darién|Emberá|Herrera|Kuna Yala|Los Santos|Ngöbe Buglé|Panamá|Veraguas"],
  ["Papua New Guinea","PG","Central Province|Chimbu Province|East New Britain Province|East Sepik Province|Eastern Highlands Province|Enga Province|Gulf Province|Kiriwina Island|Madang Province|Manus Province|Milne Bay Province|Morobe Province|National Capital District|New Ireland Province|North Solomons Province|Northern Province|Southern Highlands Province|West New Britain Province|West Sepik Province|Western Highlands Province|Western Province"],
  ["Paraguay","PY","Alto Paraguay|Alto Paraná|Amambay|Asunción - Distrito Capital|Boquerón|Caaguazú|Caazapá|Canindeyú|Central|Concepción|Cordillera|Guairá|Itapúa|Misiones|Ñeembucú|Paraguarí|Presidente Hayes|San Pedro"],
  ["Peru","PE","Amazonas|Ancash|Apurímac|Arequipa|Ayacucho|Cajamarca|Callao|Cusco|Huancavelica|Huánuco|Ica|Junín|La Libertad|Lambayeque|Lima|Loreto|Madre de Dios|Moquegua|Pasco|Piura|Puno|San Martin|Tacna|Tumbes|Ucayali"],
  ["Philippines","PH","Autonomous Region in Muslim Mindanao|Bicol Region|Cagayan Valley|Calabarzon|Caraga|Central Luzon|Central Visayas|Cordillera Administrative Region|Davao Region|Eastern Visayas|Ilocos Region|Mimaropa|National Capital Region|Northern Mindanao|Soccsksargen|Western Visayas|Zamboanga Peninsula"],
  ["Pitcairn","PN","Pitcairn Islands"],
  ["Poland","PL","Dolnośląskie|Kujawsko-Pomorskie|Łódzkie|Lubelskie|Lubuskie|Małopolskie|Mazowieckie|Opolskie|Podkarpackie|Podlaskie|Pomorskie|Śląskie|Świętokrzyskie|Warmińsko-Mazurskie|Wielkopolskie|Zachodniopomorskie"],
  ["Portugal","PT","Aveiro|Beja|Braga|Bragança|Castelo Branco|Coímbra|Évora|Faro|Guarda|Ilha da Graciosa|Ilha da Madeira|Ilha das Flores|Ilha de Porto Santo|Ilha de Santa Maria|Ilha de São Jorge|Ilha de São Miguel|Ilha do Corvo|Ilha do Faial|Ilha do Pico|Ilha Terceira|Leiria|Lisboa|Portalegre|Porto|Santarém|Setúbal|Viana do Castelo|Vila Real|Viseu"],
  ["Puerto Rico","PR","Isla de Puerto Rico"],
  ["Qatar","QA","Al Dayyan|Al Khor|Al Rayyan|Al Wakra|Doha|Madinat Al Shamal|Umm Slal"],
  ["Réunion","RE","Région Réunion"],
  ["Romania","RO","Bucureşti - Ilfov|Centru|Nord-Est|Nord-Vest|Sud Muntenia|Sud-Est|Sud-Vest Oltenia|Vest a României"],
  ["Russian Federation","RU","Adygea Republic|Altai Krai|Altai Republic|Amur Oblast|Arkhangelsk Oblast|Astrakhan Oblast|Bashkortostan Republic|Belgorod Oblast|Bryansk Oblast|Buryatia Republic|Chechen Republic|Chelyabinsk Oblast|Chitinskaya Oblast|Chukotka Autonomous Okrug|Chuvashia Republic|Dagestan Republic|Ingushetia Republic|Irkutsk Oblast|Ivanovo Oblast|Jewish Autonomous Oblast|Kabardino-Balkaria Republic|Kaliningrad Oblast|Kalmykia Republic|Kaluga Oblast|Kamchatka Krai|Karachay-Cherkessia Republic|Karelia Republic|Kemerovo Oblast|Khabarovsk Krai|Khakassia Republic|Kirov Oblast|Komi republic|Kostroma Oblast|Krasnodar Krai|Krasnoyarsk Krai|Kurgan Oblast|Kursk Oblast|Leningrad Oblast|Lipetsk Oblast|Magadan Oblast|Mari El Republic|Mordovia Republic|Moscow|Moscow Oblast|Murmansk Oblast|Nizhny Novgorod Oblast|North Ossetia-Alania Republic|Novgorod Oblast|Novosibirsk Oblast|Omsk Oblast|Orenburg Oblast|Oryol Oblast|Penza Oblast|Perm Krai|Primorsky Krai|Pskov Oblast|Rostov Oblast|Ryazan Oblast|Saint Petersburg|Sakha Republic|Sakhalin Oblast|Samara Oblast|Saratov Oblast|Smolensk Oblast|Stavropol Krai|Sverdlovsk Oblast|Tambov Oblast|Tatarstan Republic|Tomsk Oblast|Tula Oblast|Tuva Republic|Tver Oblast|Tyumen Oblast|Udmurt Republic|Ulyanovsk Oblast|Vladimir Oblast|Volgograd Oblast|Vologda Oblast|Voronezh Oblast|Yaroslavl Oblast"],
  ["Rwanda","RW","Est|Nord|Ouest|Sud|Ville de Kigali"],
  ["Western Sahara","EH","Guelmim-Es Semara|Laâyoune-Boujdour-Sakia el Hamra|Oued Ed Dahab-Lagouira"],
  ["Saint Barthélemy","BL","Au Vent|Sous le Vent"],
  ["Saint Kitts and Nevis","KN","Nevis|Saint Kitts"],
  ["Saint Lucia","LC","Anse la Raye Quarter|Castries Quarter|Choiseul Quarter|Dauphin Quarter|Dennery Quarter|Gros Islet Quarter|Laborie Quarter|Micoud Quarter|Praslin Quarter|Soufrière Quarter|Vieux Fort Quarter"],
  ["Saint Martin (French part)","MF","Arrondissement de Saint-Martin"],
  ["Saint Pierre and Miquelon","PM","Île de Saint-Pierre-et-Miquelon"],
  ["Saint Vincent and the Grenadines","VC","Charlotte Parish|Grenadines Parish|Saint Andrew Parish|Saint David Parish|Saint George Parish|Saint Patrick Parish"],
  ["Samoa","WS","Savai'i|Upolu"],
  ["San Marino","SM","Acquaviva|Borgo Maggiore|Chiesanuova|Domagnano|Faetano|Fiorentino|Montegiardino|Serravalle"],
  ["Saint Helena, Ascension and Tristan da Cunha","SH","Ascención Island|Saint Helena|Tristan da Cunha Islands"],
  ["São Tomé and Príncipe","ST","Príncipe|Sao Tome"],
  ["Saudi Arabia","SA","Al Bahah|Al Jawf|Al Madinah|Al Qaseem|Aseer|Eastern|Hail|Jazan|Makkah|Najran|Northern Border|Tabouk"],
  ["Senegal","SN","Dakar|Diourbel|Fatick|Kaffrine|Kaolack|Kédougou|Kolda|Louga|Matam|Saint-Louis|Sédhiou|Tambacounda|Thiès|Ziguinchor"],
  ["Serbia","RS","Centralna Srbija|Kosovo|Vojvodina"],
  ["Seychelles","SC","Greater Victoria|Inner Islands|North Mahé|Outer Islands|South Mahé|West Mahé"],
  ["Sierra Leone","SL","Eastern|Northern|Southern|Western Area"],
  ["Singapore","SG","Central Singapore|North East|North West|South East|South West"],
  ["Sint Maarten (Dutch part)","SX","Collectivity of Saint Martin"],
  ["Slovakia","SK","Banskobystrický kraj|Bratislavský kraj|Košický kraj|Nitriansky kraj|Prešovský kraj|Trenčiansky kraj|Trnavský kraj|Žilinský kraj"],
  ["Slovenia","SI","Gorenjska|Goriška|Jugovzhodna Slovenija|Koroška|Notranjsko-kraška|Obalno-kraška|Osrednjeslovenska|Podravska|Pomurska|Savinjska|Spodnjeposavska|Zasavska"],
  ["Solomon Islands","SB","Central|Guadalcanal|Isabel|Makira|Malaita|Temotu|Western"],
  ["Somalia","SO","Bakool|Banaadir|Bari|Bay|Galguduud|Gedo|Hiiraan|Jubbada Dhexe|Jubbada Hoose|Mudug|Nugaal|Sanaag|Shabeellaha Dhexe|Shabeellaha Hoose|Togdheer|Woqooyi Galbeed"],
  ["South Africa","ZA","Eastern Cape|Free State|Gauteng|KwaZulu-Natal|Limpopo|Mpumalanga|North West|Northern Cape|Western Cape"],
  ["South Georgia and the South Sandwich Islands","GS","South Georgia and the South Sandwich Islands"],
  ["Korea, Republic of (South)","KR","Busan|Chungcheongbuk-do|Chungcheongnam-do|Daegu|Daejeon|Gangwon-do|Gwangju|Gyeonggi-do|Gyeongsangbuk-do|Gyeongsangnam-do|Incheon|Jeju-do|Jeollabuk-do|Jeollanam-do|Seoul|Ulsan"],
  ["South Sudan","SS","Central Equatoria|Eastern Equatoria|Jonglei|Lakes|Northern Bahr al Ghazal|Unity|Upper Nile|Warrap|Western Bahr el Ghazal|Western Equatoria"],
  ["Spain","ES","Andalucía|Aragón|Asturias|Cantabria|Castilla - La Mancha|Castilla y León|Cataluña|Ceuta|Extremadura|Galicia|Islas Baleares|Islas Canarias|La Rioja|Madrid|Melilla|Murcia|Navarra|País Vasco|Valencia"],
  ["Sri Lanka","LK","Central|Eastern|North Central|North Western|Northern|Sabaragamuwa|Southern|Uva|Western"],
  ["Sudan","SD","Blue Nile|Gadarif|Gezira|Kassala|Khartoum|North Darfur|North Kordofan|Northern|Red Sea|River Nile|Sennar|South Darfur|South Kordofan|West Darfur|West Kordofan|White Nile"],
  ["Suriname","SR","Brokopondo|Commewijne|Coronie|Marowijne|Nickerie|Para|Paramaribo|Saramacca|Sipaliwini|Wanica"],
  ["Svalbard and Jan Mayen","SJ","Norway Overseas territories"],
  ["Swaziland","SZ","Hhohho|Lubombo|Manzini|Shiselweni"],
  ["Sweden","SE","Blekinge Län|Dalarnas Län|Gävleborgs Län|Gotlands Län|Hallands Län|Jämtlands Län|Jönköpings Län|Kalmar Län|Kronobergs Län|Norrbottens Län|Örebro Län|Östergötlands Län|Skåne Län|Södermanlands Län|Stockholms Län|Uppsala Län|Värmlands Län|Västerbottens Län|Västernorrlands Län|Västmanlands Län|Västra Götalands Län"],
  ["Switzerland","CH","Aargau|Appenzell Ausserrhoden|Appenzell Innerhoden|Basel-Landschaft|Basel-Stadt|Bern|Fribourg|Genève|Glarus|Graubünden|Jura|Luzern|Neuchâtel|Nidwalden|Obwalden|Sankt Gallen|Schaffhausen|Schwyz|Solothurn|Thurgau|Ticino|Uri|Valais|Waadt|Zug|Zürich"],
  ["Syrian Arab Republic","SY","Al Hassakah|Aleppo|Al-Ladhiqiyah|Al-Qunaytirah|Al-Raqqah|Al-Suwayda|Damascus|Daraa|Dayr az Zawr|Hama|Homs|Idlib|Rif Dimashq|Tartus"],
  ["Taiwan, Republic of China","TW","Changhua County|Chiayi City|Chiayi County|Hsinchu City|Hsinchu County|Hualien County|Kaohsiung City|Kaohsiung County|Keelung City|Kinmen County|Lienchiang County|Miaoli County|Nanhai Islands|Nantou County|Penghu County|Pingtung County|Taichung City|Taichung County|Tainan City|Tainan County|Taipei City|Taipei County|Taitung County|Taoyuan County|Yilan County|Yunlin County"],
  ["Tajikistan","TJ","Karategin|Khatlon|Kŭhistoni Badakhshon|Sughd"],
  ["Tanzania, United Republic of","TZ","Arusha|Dar es Salaam|Dodoma|Iringa|Kagera|Kigoma|Kilimanjaro|Lindi|Manyara|Mara|Mbeya|Morogoro|Mtwara|Mwanza|Pemba North|Pemba South|Pwani|Rukwa|Ruvuma|Shinyanga|Singida|Tabora|Tanga|Zanzibar North|Zanzibar South and Central|Zanzibar West"],
  ["Thailand","TH","Central|East|North|Northeast|South|West"],
  ["Togo","TG","Centrale|Kara|Maritime|Plateaux|Savannes"],
  ["Tokelau","TK","Tokelau"],
  ["Tonga","TO","'Eua|Ha'apai|Niuas|Tongatapu|Vava'u"],
  ["Trinidad and Tobago","TT","Arima|Chaguanas|Couva-Tabaquite-Talparo|Diego Martin|Penal-Debe|Point Fortin|Port of Spain|Princes Town|Rio Claro-Mayaro|San Fernando|San Juan-Laventille|Sangre Grande|Siparia|Tunapuna-Piarco"],
  ["Tunisia","TN","Ariana|Béja|Ben Arous|Bizerte|Gabès|Gafsa|Jendouba|Kairouan|Kasserine|Kebili|La Manouba|Le Kef|Mahdia|Medenine|Monastir|Nabeul|Sfax|Sidi Bouzid|Siliana|Sousse|Tataouine|Tozeur|Tunis|Zaghouan"],
  ["Turkey","TR","Adana|Adiyaman|Afyonkarahİsar|Ağri|Aksaray|Amasya|Ankara|Antalya|Ardahan|Artvİn|Aydin|Balikesİr|Bartin|Batman|Bayburt|Bİlecİk|Bİngöl|Bİtlİs|Bolu|Burdur|Bursa|Çanakkale|Çankiri|Çorum|Denİzlİ|Dİyarbakir|Düzce|Edİrne|Elaziğ|Erzİncan|Erzurum|Eskİşehİr|Gazİantep|Gİresun|Gümüşhane|Hakkarİ|Hatay|Iğdir|Isparta|İstanbul|İzmİr|Kahramanmaraş|Karabük|Karaman|Kars|Kastamonu|Kayserİ|Kİlİs|Kirikkale|Kirklarelİ|Kirşehİr|Kocaelİ|Konya|Kütahya|Malatya|Manİsa|Mardİn|Mersİn|Muğla|Muş|Nevşehİr|Nİğde|Ordu|Osmanİye|Rİze|Sakarya|Samsun|Şanliurfa|Sİİrt|Sinop|Şirnak|Sİvas|Tekİrdağ|Tokat|Trabzon|Tuncelİ|Uşak|Van|Yalova|Yozgat|Zonguldak"],
  ["Turkmenistan","TM","Aşgabat|Balkan / Krasnovodsk|Daşoguz / Tashauz|Lebap / Chardzhou|Mary"],
  ["Turks and Caicos Islands","TC","Caicos Islands|Turks Islands"],
  ["Tuvalu","TV","Funafuti|Nanumaga|Nanumea|Niulakita|Niutao|Nui|Nukufetau|Nukulaelae|Vaitupu"],
  ["Virgin Islands, U.S.","VI","Virgin Islands"],
  ["Uganda","UG","Adjumani|Amolatar|Amuria|Amuru|Apac|Arua|Budaka|Bugiri|Bukedea|Bundibugyo|Bushenyi|Busia|Butaleja|Dokolo|Gulu|Hoima|Ibanda|Iganga|Isingiro|Jinja|Kaabong|Kabale|Kabarole|Kaberamaido|Kalangala|Kaliro|Kampala|Kamuli|Kamwenge|Kanungu|Kapchorwa|Kasese|Katakwi|Kayunga|Kibaale|Kiboga|Kiruhuura|Kisoro|Kitgum|Koboko|Kotido|Kumi|Kyenjojo|Lira|Luwero|Lyantonde|Manafwa|Masaka|Masindi|Mayuge|Mbale|Mbarara|Mityana|Moroto|Moyo|Mpigi|Mubende|Mukono|Nakapiripirit|Nakaseke|Nakasongola|Namutumba|Nebbi|Ntungamo|Nyadri|Oyam|Pader|Pallisa|Rakai|Sembabule|Sironko|Soroti|Tororo|Wakiso|Yumbe"],
  ["Ukraine","UA","Avtonomna Respublika Krym|Cherkas'ka Oblast|Chernihivs'ka Oblast|Chernivets'ka Oblast|Dnipropetrovs'ka Oblast|Donets'ka Oblast|Ivano-Frankivs'ka Oblast|Kharkivs'ka Oblast|Khersons'ka Oblast|Khmel'nyts'ka Oblast|Kirovohrads'ka Oblast|Kyïv|Kyïvs'ka Oblast|Luhans'ka Oblast|L'vivs'ka Oblast|Mykolaivs'ka Oblast|Odes'ka Oblast|Poltavs'ka Oblast|Rivnens'ka Oblast|Sevastopol|Sums'ka Oblast|Ternopil's'ka Oblast|Vinnyts'ka Oblast|Volyns'ka Oblast|Zakarpats'ka Oblast|Zaporiz'ka Oblast|Zhytomyrs'ka Oblast"],
  ["United Arab Emirates","AE","Abu Dhabi|Ajman|Dubai|Fujairah|Ras al Khaimah|Sharjah|Umm Al Quwain"],
  ["United Kingdom","GB","Anegada|Anguilla|Anguillita Island|Antrim|Armagh|Ascención Island|Barren Island|Beauchene Island|Beaver Island|Bedfordshire|Berkshire|Bleaker Island|Blowing Rock|Box Island|Brocken Island|Buckinghamshire|Burnt Island|Caicos Islands|Cambridgeshire|Carcass Island|Cayman Brac|Chagos Islands|Cheshire|Christmas Island|City of Bristol|City of Hamilton|Cornwall|County of Herefordshire|Cove Cay|Cow Island|Crocus Cay|Cross Island|Cumbria|Deadman's Cay|Derbyshire|Devon|Devonshire Parish|Dog Island|Dorset|Double Creek Islands|Down|Dry Island|Durham|Dyke Island|East Cay|East Falkland|East Riding of Yorkshire|East Sussex|Eddystone Island|Essex|Fermanagh|George Island|Gloucestershire|Golding Island|Grand Cayman|Great Island|Greater London|Greater Manchester|Hamilton Parish|Hampshire|Hertfordshire|Isle of Wight|Jason Islands|Jost Van Dyke|Kent|Keppel Island|Lancashire|Leicestershire|Lincolnshire|Little Cayman|Little Island|Little Scrub Island|Londonderry|Merseyside|Mid Cay|Middle Island|New Island|Norfolk|North Cay|North Yorkshire|Northamptonshire|Northumberland|Nottinghamshire|Other Islands|Outer Island|Oxfordshire|Paget Parish|Passage Island|Peat Island|Pebble Island|Pembroke Parish|Philmore Island|Pitcairn Islands|Port Patterson|Prickly Pear Cays|Rabbit Island|Ruggles Island|Rutland|Saint Anthony Parish|Saint Georges Parish|Saint Helena|Saint Peter Parish|Sandbar Island|Sandy Island/Sand Island|Sandys Parish|Saunders Island|Scilly Cay|Scotland region|Scrub Island|Sea Lion Island|Seal Island|Sedge Island|Shropshire|Smith's Parish|Sombrero/Hat Island|Somerset|South Cay|South Wager Island|South Yorkshire|Southampton Parish|Speedwell Island|Spring Point Island|St. George's Parish|Staats Island|Staffordshire|Suffolk|Surrey|Swan Island|Tickel Island|Tortola|Town of St. George|Tristan da Cunha Islands|Turks Islands|Tussac Island|Tyne and Wear|Tyrone|Virgin Gorda|Wales region|Warwick Parish|Warwickshire|Weddell Island|West Cay|West Falkland|West Island|West Midlands|West Point Island|West Sussex|West Swan island|West Yorkshire|Wiltshire|Wolfe Island|Worcestershire"],
  ["United States","US","Alabama|Alaska|American Samoa|Arizona|Arkansas|Armed Forces - Americas|Armed Forces - Europe/Africa/Canada|Armed Forces - Pacific|California|Colorado|Connecticut|Delaware|District of Columbia|Federated States of Micronesia|Florida|Georgia|Guam|Hawaii|Idaho|Illinois|Indiana|Iowa|Kansas|Kentucky|Louisiana|Maine|Marshall Islands|Maryland|Massachusetts|Michigan|Minnesota|Minor Outlying Islands|Mississippi|Missouri|Montana|Nebraska|Nevada|New Hampshire|New Jersey|New Mexico|New York|North Carolina|North Dakota|Northern Mariana Islands|Ohio|Oklahoma|Oregon|Palau|Pennsylvania|Puerto Rico|Rhode Island|South Carolina|South Dakota|Tennessee|Texas|Utah|Vermont|Virgin Islands|Virginia|Washington|West Virginia|Wisconsin|Wyoming"],
  ["United States Minor Outlying Islands","UM","Minor Outlying Islands"],
  ["Uruguay","UY","Artigas|Canelones|Cerro Largo|Colonia|Durazno|Flores|Florida|Lavalleja|Maldonado|Montevideo|Paysandú|Rio Negro|Rivera|Rocha|Salto|San José|Soriano|Tacuarembó|Treinta y Tres"],
  ["Uzbekistan","UZ","Andijan Province|Bukhara Province|Fergana Province|Jizzakh Province|Karakalpakstan republic|Namangan Province|Navoiy Province|Qashqadaryo Province|Samarqand Province|Sirdaryo Province|Surxondaryo Province|Tashkent City|Tashkent Province|Xorazm Province"],
  ["Vanuatu","VU","Malapa|Pénama|Sanma|Shéfa|Taféa|Torba"],
  ["Vatican City State (Holy See)","VA","Città del Vaticano"],
  ["Venezuela, Bolivarian Republic of","VE","Amazonas|Anzoátegui|Apure|Aragua|Barinas|Bolívar|Carabobo|Caracas|Cojedes|Delta Amacuro|Dependencias Federales|Falcón|Guárico|Lara|Mérida|Miranda|Monagas|Nueva Esparta|Portuguesa|Sucre|Táchira|Trujillo|Vargas|Yaracuy|Zulia"],
  ["Viet Nam","VN","Bắc Trung Bộ|Đông Bắc|Đồng Bằng Sông Cửu Long|Đồng Bằng Sông Hồng|Đông Nam Bộ|Nam Trung Bộ|Tây Bắc|Tây Nguyên"],
  ["Wallis and Futuna","WF","Région Wallis-et-Futuna"],
  ["Yemen","YE","Abyan Governorate|Ad Dali|Adan|Al Hudaydah|Al Jawf Governorate|Al Mahrah Governorate|Al Mahwit Governorate|Al-Baidhah|Amran|Dhamar Governorate|Hadhramaut|Hajjah|Ibb|Laḩij|Ma'rib|Raymah Governorate|Sa'Dah|Sana`a Governorate|Sana'a Municipality|Shabwah Governorate|Ta`izz"],
  ["Zambia","ZM","Central|Copperbelt|Eastern|Luapula|Lusaka|Northern|North-Western|Southern|Western"],
  ["Zimbabwe","ZW","Bulawayo|Harare|Manicaland|Mashonaland Central|Mashonaland East|Mashonaland West|Masvingo|Matabeleland North|Matabeleland South|Midlands"]
];